package com.example.trillo.enums;

public enum NotificationType {
    BOARD_INVITE,
    BOARD_INVITATION,
    INVITATION_ACCEPTED,
    INVITATION_DECLINED,
    JOIN_REQUEST,
    MEMBER_REMOVED,
    CARD_ASSIGNED,
    DEADLINE_REMINDER,
    CARD_UPDATED,
    COMMENT_ADDED,
    MEMBER_JOINED,
    TASK_ASSIGNED,
    TASK_STATUS_CHANGED,
    TASK_DUE_SOON,
    TASK_OVERDUE,
    COMMENT,
    MENTION
}
